name: CMake Tests
on: 
  push:

jobs:
  buildTest:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        compiler: [g++]
      
    steps:

    - name: Update packages
      run: |
        sudo apt-get update
        sudo apt-get install -yq valgrind

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      run: ./install.sh .. ${{matrix.build_type}} ${{matrix.compiler}}

    - name: Run Unit Tests
      run: |
        cd ../build-class
        make
        ./fem_main --reporter compact --success

    - name: Create Sample Mesh File
      run: |
        cat <<EOF > triangle1.msh
        \$MeshFormat
        2.2 0 8
        \$EndMeshFormat
        \$Nodes
        3
        1 0.0 0.0 0.0
        2 1.0 0.0 0.0
        3 0.0 1.0 0.0
        \$EndNodes
        \$Elements
        1
        1 2 1 0 1 2 3
        \$EndElements
        EOF

    - name: Run FEM Driver with triangle1.msh
      run: |
        ./fem_main triangle1.msh x2y
